steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', "https://source.developers.google.com/p/${_PROJECT}/r/${_REPO_NAME}"]

- name: maven:3.3-jdk-8
  entrypoint: mvn
  args: ['test']

- name: maven:3.3-jdk-8
  entrypoint: mvn
  args: ['clean','package','-Dmaven.test.skip=true']

- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'us-central1-docker.pkg.dev/${_PROJECT}/javaimage/jvimg:$SHORT_SHA']

images: ['us-central1-docker.pkg.dev/${_PROJECT}/javaimage/jvimg:$SHORT_SHA']

artifacts:
  mavenArtifacts:
  - repository: 'https://us-central1-maven.pkg.dev/${_PROJECT}/mavenregistry'
    path: 'kubernetes/target/kubernetes-1.0-AMIT.war'
    artifactId: 'kubernetes'
    groupId: 'k8sDemo.devops.gcp'
    version: '1.2-AMIT'

substitutions:
  _PROJECT: kubernetes-gcp-383911
  _REPO_NAME: github_masudd11_kubernetes-docker-gcp-deployment

options:
  # substitutionOption: 'ALLOW_LOOSE'
  logging: CLOUD_LOGGING_ONLY
  requestedVerifyOption: VERIFIED